### PR TITLE
feat: allow configuring internal api routes

### LINKED ISSUE #95: Are the internal routes configurable
can we use other routes than `/api/login` and `/api/register` for the internal routes?

These conflict with routes that my app is using for other purposes.

### LINKED ISSUE #123: getUser is blowing up in server handler
I have a brand new Nuxt 3 app and a `/api/me` nuxt server handler which will attach a few extra things stored in a database. I'm getting this error: `ERROR  [nitro] [unhandledRejection] Compact JWS must be a string or Uint8Array` and this is the code:

```
export default defineEventHandler(async (event) => {
  const kinde = event.context.kinde
  const user = await kinde.getUser()

  return {
    doesnt: 'matter'
  }
})
```

Full stack trace:
```
 ERROR  [nitro] [unhandledRejection] Compact JWS must be a string or Uint8Array

  at compactVerify (node_modules/jose/dist/node/esm/jws/compact/verify.js:9:15)
  at jwtVerify (node_modules/jose/dist/node/esm/jwt/verify.js:5:28)
  at node_modules/@kinde-oss/kinde-typescript-sdk/dist/sdk/utilities/token-utils.js:142:45
  at step (node_modules/@kinde-oss/kinde-typescript-sdk/dist/sdk/utilities/token-utils.js:32:23)
  at Object.next (node_modules/@kinde-oss/kinde-typescript-sdk/dist/sdk/utilities/token-utils.js:13:53)
  at fulfilled (node_modules/@kinde-oss/kinde-typescript-sdk/dist/sdk/utilities/token-utils.js:4:58)
```

FWIW, `await kinde.isAuthenticated()` returns true, so I'm not sure how it would know if someone is authenticated or not if some cookie/jwt/etc. wasn't being passed and successfully verified.

My .env is very barebones and I basically followed your quick start when I selected Nuxt as my existing application:

```
NUXT_KINDE_PASSWORD=nope
NUXT_KINDE_CLIENT_ID=nope
NUXT_KINDE_CLIENT_SECRET=nope
NUXT_KINDE_AUTH_DOMAIN=https://mydomain.kinde.com
NUXT_KINDE_REDIRECT_URL=http://localhost:3000/api/callback
NUXT_KINDE_LOGOUT_REDIRECT_URL=http://localhost:3000
NUXT_KINDE_POST_LOGIN_REDIRECT_URL=http://localhost:3000/dashboard
```

Do you have any suggestions?

### PR DESCRIPTION
**Pull request by felix-dolderer**
### 🔗 Linked issue

resolves #95 

### ❓ Type of change

- [x] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [x] 👌 Enhancement (improving an existing functionality)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Make the internal apiRoutes configurable. This can be useful if the default apiRoutes (e.g. `/api/login`) are already in use for some other purpose.

### CODE REVIEW

**Comment by DanielRivers** [comment]
Great!  Thank you for this.  It was next on my list after the current active PR I am finishing off.

**Comment by felix-dolderer** [comment]
I left one TODO comment in there. Didn't have time to figure out how to get the runtime config typed exactly correct.

**Review by danielroe — APPROVED** [review]
This looks great - thank you! ❤️

**Review by DanielRivers — APPROVED** [review]
Looks great to me!

**Pull request merged**
