### PR TITLE
fix: update sessionManager to use cookies (#24)

### PR DESCRIPTION
**Pull request by DanielRivers**
# Problem:

When returning from the auth flow on Safari the session state appears to be lost. (https://github.com/nuxt-modules/kinde/issues/24)

# Solution:

This switches to use cookies in the session manager

### CODE REVIEW

**Comment by DanielRivers** [comment]
This also resolves #14

**Review by danielroe — COMMENTED** [review]
This looks like it might be insecure - the user could simply define their own cookie value?

Perhaps instead we could update the `config` to change the cookie settings for `getSession`?

**Review by danielroe — CHANGES_REQUESTED** [review]
I think we should use built in h3 storage, but should probably configure `SameSite` (which is likely cause of the issue you describe).

https://web.dev/articles/samesite-cookies-explained#explicitly_state_cookie_usage_with_the_samesite_attribute

**Comment by DanielRivers** [comment]
Yes, I want to set `sameSite`, `secure` and `httpOnly`

**Comment by danielroe** [comment]
You can do that here:

https://github.com/nuxt-modules/kinde/blob/main/src/runtime/server/middleware/kinde.ts#L23-L26

**Comment by danielroe** [comment]
I've merged https://github.com/nuxt-modules/kinde/pull/59. It might also resolve what you were aiming for - let me know 🙏

**Comment by DanielRivers** [comment]
> I've merged #59. It might also resolve what you were aiming for - let me know 🙏

Thanks @danielroe I will give this a go and report back!

**Comment by DanielRivers** [comment]
@danielroe Sadly the safari issue remains, I hope to get round to it this week. Issue https://github.com/nuxt-modules/kinde/issues/24 remains

**Comment by danielroe** [comment]
Okay, we may just need to change the session cookie settings (which are now configurable).

**Comment by DanielRivers** [comment]
Closed as fixed in another PR

**Pull request closed without merging**
